# Generated by Django 4.1.7 on 2023-03-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='ATM.accounts'),
        ),
    ]
