# Generated by Django 4.1.7 on 2023-03-29 16:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0002_alter_transactions_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='date_opened',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('AO', 'Account Opened'), ('AC', 'Account Closed'), ('WD', 'Withdrawal'), ('DP', 'Deposit'), ('TR', 'Transfer')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_id', to='ATM.accounts'),
        ),
    ]
