# Generated by Django 4.1.7 on 2023-03-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0004_alter_accounts_options_alter_transactions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='success',
            field=models.BooleanField(choices=[(True, 'Success'), (False, 'Error')], default=True),
        ),
    ]
