# Generated by Django 4.1.7 on 2023-03-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0005_transactions_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='success',
        ),
    ]
